### PR TITLE
Simple touch controls 

### PR DESCRIPTION
**Pull request by Quest84**
Hey! I added simple touch controls and some tweaks in the inputs and the status bar. 
I don't know how to make touch gestures so it's just simple touches to move between pages and zoom heh
Also I uploaded the binary on the releases section on my fork

### CODE REVIEW

**Comment by SeanOMik** [comment]
Awesome, thanks again for continuing to develop this. How would you feel about getting permissions on this repo so you don't need to develop on your own branch?

I think its good to say that my hacked switch is completely broken lol

**Comment by Quest84** [comment]
Yeah, that would be cool. I don't know how much more can I contribute, maybe fixing the scroll down on the list of books or implementing touch gestures (I need to research more about this).
What happened to your switch? It's a softbrick or a physical damage?

**Comment by SeanOMik** [comment]
> 
> 
> Yeah, that would be cool. I don't know how much more can I contribute, maybe fixing the scroll down on the list of books or implementing touch gestures (I need to research more about this).

That's fine, I'll give you access anyway. I just sent you a collab invite just accept that and *I think* you'll have access. I've never given anyone access to a public repo haha.


> What happened to your switch? It's a softbrick or a physical damage?

I think it's physical damage. Its something to do with the SD card. The switch works for a few minutes, maybe a few read/write operations idk, and then applications (official and homebrew) start freezing, or moving extremely slow until I get a random userland-related crash. Then I reboot to atmosphere payload (in the atmosphere crash screen) and it gives me an error saying something like: "Failed to Initialize Micro SD card." A while ago I replaced the micro sd card module and it fixed it for a few days, but then it started happening again. I also got a new micro sd card after that and it fixed it for maybe a day but started happening again.

When it crashed only a few times a day I let my sister use it for about a week and it just stopped having micro sd card issues. Even when I got it back, it worked great then when I had to take the card out to update, it started crashing again. I don't think I've mentioned it in that wall of text, but at first, it happened a few times a week, then once a day, multiple times a day, to literally 5 minutes in use of the switch.

The **only** thing I can think of is that the pins of the motherboard to the sd card module are broken/bent, and somehow my sister knocked it in the right place, when I took the sd card out causing me to apply pressure onto the module and it moved it out of place. I just haven't opened the switch again since I stripped a screw last time I opened it and would rather not do that again. I am still willing to open it again though, just haven't felt like it haha.

Sorry for that massive wall of text. If you have any ideas, I'll be willing to try them. However, I'm going on vacation on Monday for a week and then preparing for my move to college, so it might take a while for me to try them.

**Comment by Quest84** [comment]
> That's fine, I'll give you access anyway. I just sent you a collab invite just accept that and I think you'll have access. I've never given anyone access to a public repo haha.

I have access now, thanks!

> Sorry for that massive wall of text. If you have any ideas, I'll be willing to try them. However, I'm going on vacation on Monday for a week and then preparing for my move to college, so it might take a while for me to try them.

Yeah don't worry, I guess it's the socket of the micro sd module, that thing looks fragile. I've opened the switch a few times and I always think I'll break that thing if I connect it in the wrong way. You could check if the socket has a missing pin and maybe you could replace the socket or just bridge the missing one with a wire.
Good luck on your vacations and at the college!

Also check this maybe it will help you:
[Fourm post](https://www.tronicsfixforum.com/t/missing-pin-on-nintendo-switch-mb-socket-that-holds-the-sd-card-reader/1319/28)

**Comment by SeanOMik** [comment]
> Good luck on your vacations and at the college!
Thanks!

> Also check this maybe it will help you:
> [Fourm post](https://www.tronicsfixforum.com/t/missing-pin-on-nintendo-switch-mb-socket-that-holds-the-sd-card-reader/1319/28)

Oh, I didn't think of the actual pins on the motherboard being broken, I'll check that next time I open it.

**Pull request merged**
